#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Converter.Resource", IsApplication=true)]

namespace Converter
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050001
			public const int degrees_array = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int length_array = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int radiansDegrees_array = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int weight_array = 2131034115;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow_forward = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int back = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_text_color = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_transparent = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_transform_black_24dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int subdirectory = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06001d
			public const int MyButton = 2131099677;
			
			// aapt resource value: 0x7f060006
			public const int MyButtonDeg = 2131099654;
			
			// aapt resource value: 0x7f060011
			public const int MyButtonLength = 2131099665;
			
			// aapt resource value: 0x7f060028
			public const int MyButtonWeight = 2131099688;
			
			// aapt resource value: 0x7f060008
			public const int degreesFormulasButton = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int dialogDegreesDismissBtn = 2131099658;
			
			// aapt resource value: 0x7f060015
			public const int dialogDismissBtn = 2131099669;
			
			// aapt resource value: 0x7f060021
			public const int dialogRadiansDegreesDismissBtn = 2131099681;
			
			// aapt resource value: 0x7f060016
			public const int fragmentContainer = 2131099670;
			
			// aapt resource value: 0x7f06001a
			public const int fromSpinner = 2131099674;
			
			// aapt resource value: 0x7f060003
			public const int fromSpinnerDeg = 2131099651;
			
			// aapt resource value: 0x7f06000e
			public const int fromSpinnerLength = 2131099662;
			
			// aapt resource value: 0x7f060025
			public const int fromSpinnerWeight = 2131099685;
			
			// aapt resource value: 0x7f060002
			public const int fromTextViewDegrees = 2131099650;
			
			// aapt resource value: 0x7f06000d
			public const int fromTextViewLength = 2131099661;
			
			// aapt resource value: 0x7f060019
			public const int fromTextViewRadiansDegrees = 2131099673;
			
			// aapt resource value: 0x7f060024
			public const int fromTextViewWeight = 2131099684;
			
			// aapt resource value: 0x7f060013
			public const int lengthFormulasButton = 2131099667;
			
			// aapt resource value: 0x7f06001f
			public const int radiansDegreesFormulasButton = 2131099679;
			
			// aapt resource value: 0x7f060007
			public const int resultDeg = 2131099655;
			
			// aapt resource value: 0x7f060012
			public const int resultLength = 2131099666;
			
			// aapt resource value: 0x7f06001e
			public const int resultTxt = 2131099678;
			
			// aapt resource value: 0x7f060029
			public const int resultWeight = 2131099689;
			
			// aapt resource value: 0x7f060009
			public const int tableDegreesFormulas = 2131099657;
			
			// aapt resource value: 0x7f060014
			public const int tableLengthFormulas = 2131099668;
			
			// aapt resource value: 0x7f060020
			public const int tableRadiansDegreesFormulas = 2131099680;
			
			// aapt resource value: 0x7f06001c
			public const int toSpinner = 2131099676;
			
			// aapt resource value: 0x7f060005
			public const int toSpinnerDeg = 2131099653;
			
			// aapt resource value: 0x7f060010
			public const int toSpinnerLength = 2131099664;
			
			// aapt resource value: 0x7f060027
			public const int toSpinnerWeight = 2131099687;
			
			// aapt resource value: 0x7f060004
			public const int toTextViewDegrees = 2131099652;
			
			// aapt resource value: 0x7f06000f
			public const int toTextViewLength = 2131099663;
			
			// aapt resource value: 0x7f06001b
			public const int toTextViewRadiansDegrees = 2131099675;
			
			// aapt resource value: 0x7f060026
			public const int toTextViewWeight = 2131099686;
			
			// aapt resource value: 0x7f060001
			public const int valueDeg = 2131099649;
			
			// aapt resource value: 0x7f06000c
			public const int valueLength = 2131099660;
			
			// aapt resource value: 0x7f060000
			public const int valueTextViewDegrees = 2131099648;
			
			// aapt resource value: 0x7f06000b
			public const int valueTextViewLength = 2131099659;
			
			// aapt resource value: 0x7f060017
			public const int valueTextViewRadiansDegrees = 2131099671;
			
			// aapt resource value: 0x7f060022
			public const int valueTextViewWeight = 2131099682;
			
			// aapt resource value: 0x7f060018
			public const int valueTxt = 2131099672;
			
			// aapt resource value: 0x7f060023
			public const int valueWeight = 2131099683;
			
			// aapt resource value: 0x7f06002a
			public const int weightFormulasButton = 2131099690;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Degrees = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DegreesFormulas = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Length = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int LengthFormulas = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MainLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int RadiansDegrees = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int RadiansDegreesFormulas = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Weight = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int degreesStr = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int formula = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int fromto = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int lengthStr = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int multiplyby = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int rdStr = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int weightStr = 2130968583;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
